version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: image_scanner_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: image_scanner
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - app_network

  wordpress:
    image: wordpress:latest
    container_name: image_scanner_wp
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root123
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_CONFIG_EXTRA: "define('WP_ENVIRONMENT_TYPE', 'local');"
    ports:
      - '8081:80'
    volumes:
      - wp_data:/var/www/html
    networks:
      - app_network

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image_scanner_be
    restart: always
    depends_on:
      - mysql
      - wordpress
    environment:
      DATABASE_URL: mysql://appuser:apppass@mysql:3306/image_scanner
      WP_URL: http://wordpress
      WP_USER: admin
      WP_APP_PASSWORD: 'rb6f kTSi 50O9 db6P nTWr 6ots'
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      # - .:/app
      - /app/node_modules
    networks:
      - app_network

volumes:
  mysql_data:
  wp_data:

networks:
  app_network:
    driver: bridge
